[env:leaf]
platform = espressif32
board = esp32dev            ; TODO: change when the leaf MCU is finalized
framework = arduino
monitor_speed = 115200
lib_deps = jgromes/RadioLib@^6.6.0
build_flags = -I../common -Iinclude
